# Copyright (C) 2023-2024, Advanced Micro Devices, Inc.  All rights reserved.
#
# Author: Eddie Hung, AMD
#
# SPDX-License-Identifier: MIT
#

name: package-and-test-container
on:
  push:
  pull_request:
jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - run: |
          make distclean-and-package-submission
      - uses: actions/upload-artifact@v4
        with:
          name: hao3_submission.tar.gz
          compression-level: 0
          path: |
           hao3_submission*.tar.gz

  test-container:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Setup Apptainer
        env:
          APPTAINER_VERSION: '1.2.5'
        run: |
          wget https://github.com/apptainer/apptainer/releases/download/v${APPTAINER_VERSION}/apptainer_${APPTAINER_VERSION}_amd64.deb
          sudo dpkg -i apptainer_${APPTAINER_VERSION}_amd64.deb || true
          sudo apt-get -f install
      - uses: actions/download-artifact@v4
        with:
          name: hao3_submission.tar.gz
      - name: make test-container
        timeout-minutes: 10
        run: |
          mkdir hao3
          cd hao3
          tar xvzf ../hao3_submission*.tar.gz
          wget -q  https://github.com/Xilinx/fpga24_routing_contest/releases/latest/download/xcvu3p.device
          make test-container
      - uses: actions/upload-artifact@v4
        with:
          name: hao3_container.sif
          compression-level: 0
          path: |
           hao3/*.sif

